packages/
  core/
    src/
      security/
        ai-supervisor/
          agents/
            tenant-isolation-agent.ts
            security-analyst-agent.ts
            anomaly-detector-agent.ts
            index.ts
          skills/
            database-isolation-skill.ts
            security-protocol-skill.ts
            threat-intelligence-skill.ts
            index.ts
          vercel-integration/
            vercel-agent-factory.ts
            vercel-skill-mapper.ts
            index.ts
          ai-supervisor.module.ts
          ai-supervisor.service.ts
          index.ts
      tenants/
        database/
          schema-manager.service.ts
          tenant-database.service.ts
          isolation-validator.service.ts
        context/
          tenant-context.middleware.ts
          tenant-scoped.decorator.ts
        tenant.module.ts
        tenant.service.ts
      main.ts